### PR TITLE
Move from sensor to vacuum

### PR DESCRIPTION
**Pull request by firstof9**
* Update template from sensor to vacuum (Home Assistant 0.112)
* Add script for start command for vacuum template

### CODE REVIEW

**Comment by jeremywillans** [comment]
Will review and merge soon given 112 is now released

**Comment by jeremywillans** [comment]
Thanks, I've merged this into dev for now, I've got some extra updated to implement before master :)

**Comment by firstof9** [comment]
Nice, I hope you find the attributes helpful. I did especially for the Samsung Vacuums :)

**Comment by jeremywillans** [comment]
Yeah should be good! just need to work all this things it breaks 🤣

**Comment by firstof9** [comment]
Shouldn't break too many things lol

**Comment by jeremywillans** [comment]
Well.. firstly it needs to sit under "vacuum domain" ☹️ and references to sensor.vacuum need to be fixed but all good, moving it to vacuum is a better end result so its worth it 👍

**Comment by firstof9** [comment]
I think I missed the vacuum_location near the bottom, that might need indention under attributes or it'd throw an error.

**Comment by jeremywillans** [comment]
hmm.. this might take alot more work than i expected... the value_template field only has limited valid options and it dosent take an icon option 👎 

i might just park this is the dev branch for the time being and look at it later.

**Comment by firstof9** [comment]
Ya you get the standard vacuum icon:
image

**Pull request merged**
